# Generated by Django 4.1.5 on 2023-01-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_conduccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigencia', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
    ]
