# Generated by Django 4.1.5 on 2023-02-07 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='identificacion',
            field=models.CharField(default=datetime.datetime(2023, 2, 7, 16, 56, 33, 357660), max_length=10, unique=True),
        ),
    ]
