# Generated by Django 4.1.5 on 2023-02-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_aprendiz_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='identificacion',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
